import { Courses } from "../models/courses";

export const MOCK_DATA: Courses[] = [
  {
    imageUrl: "http://dummyimage.com/276x299.png/dddddd/000000",
    name: "Lyrica",
    count: 60,
    categories: ["item 2", "item 3", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/274x254.png/5fa2dd/ffffff",
    name: "Phenytoin Sodium",
    count: 2,
    categories: ["item 1", "item 4", "item 3"],
  },
  {
    imageUrl: "http://dummyimage.com/264x259.png/ff4444/ffffff",
    name: "Hydrocodone Bitartrate and Acetaminophen",
    count: 45,
    categories: ["item 3", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/296x276.png/cc0000/ffffff",
    name: "Arava",
    count: 49,
    categories: ["item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/279x286.png/5fa2dd/ffffff",
    name: "Bayberry Pollen",
    count: 40,
    categories: ["item 4", "item 3"],
  },
  {
    imageUrl: "http://dummyimage.com/254x263.png/cc0000/ffffff",
    name: "Fareston",
    count: 32,
    categories: ["item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/288x259.png/ff4444/ffffff",
    name: "good sense night time",
    count: 38,
    categories: ["item 1", "item 3", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/276x276.png/cc0000/ffffff",
    name: "CD HydraLife BB Eye Creme Enhancing Sunscreen Eye Illuminator Luminous Beige Broad Spectrum SPF 20",
    count: 26,
    categories: ["item 2", "item 3", "item 1"],
  },
  {
    imageUrl: "http://dummyimage.com/292x261.png/ff4444/ffffff",
    name: "Duloxetine",
    count: 4,
    categories: ["item 1", "item 3"],
  },
  {
    imageUrl: "http://dummyimage.com/266x280.png/5fa2dd/ffffff",
    name: "Fluticasone Propionate",
    count: 20,
    categories: ["item 2", "item 4", "item 3"],
  },
  {
    imageUrl: "http://dummyimage.com/293x293.png/5fa2dd/ffffff",
    name: "Claritin",
    count: 20,
    categories: ["item 3", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/276x253.png/dddddd/000000",
    name: "Glyburide",
    count: 94,
    categories: ["item 1", "item 3"],
  },
  {
    imageUrl: "http://dummyimage.com/294x252.png/cc0000/ffffff",
    name: "Pravastatin Sodium",
    count: 60,
    categories: ["item 1", "item 2", "item 3"],
  },
  {
    imageUrl: "http://dummyimage.com/280x262.png/ff4444/ffffff",
    name: "topcare lice treatment",
    count: 83,
    categories: ["item 1"],
  },
  {
    imageUrl: "http://dummyimage.com/298x261.png/5fa2dd/ffffff",
    name: "House Fly",
    count: 29,
    categories: ["item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/250x257.png/cc0000/ffffff",
    name: "Buspirone HCl",
    count: 15,
    categories: ["item 4", "item 3", "item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/300x261.png/cc0000/ffffff",
    name: "Ondansetron Hydrochloride",
    count: 74,
    categories: ["item 3", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/251x253.png/dddddd/000000",
    name: "Lithium Carbonate",
    count: 99,
    categories: ["item 2", "item 3", "item 1"],
  },
  {
    imageUrl: "http://dummyimage.com/292x283.png/cc0000/ffffff",
    name: "OXYGEN",
    count: 92,
    categories: ["item 2", "item 3", "item 1"],
  },
  {
    imageUrl: "http://dummyimage.com/254x254.png/ff4444/ffffff",
    name: "Acetaminophen",
    count: 3,
    categories: ["item 3", "item 1", "item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/291x265.png/cc0000/ffffff",
    name: "OPANA",
    count: 85,
    categories: ["item 4", "item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/285x264.png/5fa2dd/ffffff",
    name: "Alodox",
    count: 61,
    categories: ["item 1"],
  },
  {
    imageUrl: "http://dummyimage.com/273x296.png/ff4444/ffffff",
    name: "Acetaminophen and Codeine",
    count: 65,
    categories: ["item 3", "item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/258x293.png/ff4444/ffffff",
    name: "Spironolactone and Hydrochlorothiazide",
    count: 96,
    categories: ["item 1"],
  },
  {
    imageUrl: "http://dummyimage.com/281x259.png/ff4444/ffffff",
    name: "Sun Mark Tussin DM",
    count: 58,
    categories: ["item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/257x299.png/dddddd/000000",
    name: "CYZONE",
    count: 81,
    categories: ["item 2", "item 4", "item 3"],
  },
  {
    imageUrl: "http://dummyimage.com/274x251.png/ff4444/ffffff",
    name: "Pyridostigmine Bromide",
    count: 46,
    categories: ["item 4", "item 1"],
  },
  {
    imageUrl: "http://dummyimage.com/267x287.png/dddddd/000000",
    name: "Free Radical",
    count: 10,
    categories: ["item 3"],
  },
  {
    imageUrl: "http://dummyimage.com/269x279.png/cc0000/ffffff",
    name: "Oxycodone and Acetaminophen",
    count: 98,
    categories: ["item 3"],
  },
  {
    imageUrl: "http://dummyimage.com/296x264.png/5fa2dd/ffffff",
    name: "Conju Princess UV Sun Block",
    count: 7,
    categories: ["item 1", "item 3", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/278x269.png/cc0000/ffffff",
    name: "Ionite APF",
    count: 93,
    categories: ["item 1", "item 2", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/299x268.png/cc0000/ffffff",
    name: "MIDODRINE HYDROCHLORIDE",
    count: 87,
    categories: ["item 1", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/255x296.png/dddddd/000000",
    name: "Zidovudine",
    count: 65,
    categories: ["item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/292x288.png/ff4444/ffffff",
    name: "Levothyroxine Sodium",
    count: 19,
    categories: ["item 3", "item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/256x284.png/cc0000/ffffff",
    name: "Ceftriaxone",
    count: 20,
    categories: ["item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/263x298.png/5fa2dd/ffffff",
    name: "Levothyroxine Sodium",
    count: 67,
    categories: ["item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/268x276.png/cc0000/ffffff",
    name: "GUNA-COUGH",
    count: 69,
    categories: ["item 3", "item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/276x288.png/5fa2dd/ffffff",
    name: "HELIOX",
    count: 100,
    categories: ["item 3", "item 2", "item 1"],
  },
  {
    imageUrl: "http://dummyimage.com/285x279.png/cc0000/ffffff",
    name: "Furosemide",
    count: 57,
    categories: ["item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/281x251.png/ff4444/ffffff",
    name: "Premier Value Sterile Eye Drops",
    count: 98,
    categories: ["item 4", "item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/289x255.png/cc0000/ffffff",
    name: "amlodipine besylate and atorvastatin calcium",
    count: 8,
    categories: ["item 2"],
  },
  {
    imageUrl: "http://dummyimage.com/254x250.png/dddddd/000000",
    name: "Amoxapine",
    count: 47,
    categories: ["item 2", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/293x260.png/5fa2dd/ffffff",
    name: "Risperidone",
    count: 20,
    categories: ["item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/294x259.png/dddddd/000000",
    name: "TOPROLXL",
    count: 73,
    categories: ["item 1", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/273x276.png/5fa2dd/ffffff",
    name: "AcipHex",
    count: 61,
    categories: ["item 2", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/253x260.png/dddddd/000000",
    name: "Treatment Set TS348491",
    count: 6,
    categories: ["item 3", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/273x250.png/ff4444/ffffff",
    name: "Nectarine",
    count: 23,
    categories: ["item 3"],
  },
  {
    imageUrl: "http://dummyimage.com/293x260.png/dddddd/000000",
    name: "Naturasil",
    count: 21,
    categories: ["item 3", "item 1"],
  },
  {
    imageUrl: "http://dummyimage.com/293x290.png/5fa2dd/ffffff",
    name: "Midazolam",
    count: 60,
    categories: ["item 2", "item 3", "item 4"],
  },
  {
    imageUrl: "http://dummyimage.com/256x261.png/dddddd/000000",
    name: "Kiehls Since 1851 Broad Spectrum SPF 30 Sunscreen Powerful Wrinkle Reducing",
    count: 91,
    categories: ["item 1", "item 4"],
  },
];
